kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

steps:
- name: build use maven
  image: maven:3.8.5-openjdk-11
  commands:
  - mvn clean package
- name: docker build image & push
  image: plugins/docker
  # privileged: true
  settings:
    repo: chihkang/quarkus-app
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: src/main/docker/Dockerfile.jvm
    cache_from: chihkang/quarkus-app:linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    debug: true
    dry_run: true