kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: maven:3.8.5-openjdk-11
  commands:
  - cd ~/getting-started
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

- name: docker  
  image: plugins/docker
  settings:
    repo: chihkang/quarkus-app
    tags:
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password