kind: pipeline
name: default
type: docker
platform:
  os: linux
  arch: arm64
steps:
- name: test
  image: maven:3.8.5-openjdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B